### PR TITLE
Refactor into UPM package structure

### PR DESCRIPTION
**Pull request by hybridherbst**
This looks like a big change but actually it's just some folder renames and AsmDef creation.
The result is that this repository is compatible with Unity's Package Manager (UPM) and thus becomes much easier to consume and use in projects.

image

It will simply show in the Packages list instead of Assets:
image

For now I added just one sample to package.json which imports all sample scenes, but that could be split into multiple if wanted.

### CODE REVIEW

**Comment by hecomi** [comment]
I'm sorry for the late reply. After a lot of research, I decided to do a branch-based release. Here is the research article (written in Japanese, sorry about that)

- https://tips.hecomi.com/entry/2021/10/29/001304

I made this structure in uOSC and tried to do a release.

- https://github.com/hecomi/uOSC/tree/upm

For this reason, I'm going to change the directory structure a bit based on it.

**Comment by hecomi** [comment]
Now we can import uWindowCapture with Package Manager from the URL `https://github.com/hecomi/uWindowCapture.git#upm`. Thank you for your contribution!

**Comment by hybridherbst** [comment]
Usually it's not necessary to have a special branch, tag-based releases work great (you can see e.g. https://github.com/needle-tools/compilation-visualizer for an example of that).

People can either then pin the right tag when they add as a git repo, or consume the releases from OpenUPM.

**Comment by hecomi** [comment]
Just using the tag-based release is not enough for my usecases. So, I'm using GitHub Actions that is activated when new tag is pushed automatically to recreate the directory structure itself:

- https://github.com/hecomi/create-upm-branch-action

Also, I don't want to use the directory name `Samples~`. I think this is convenient for users who don't need the samples. However, for me, who does a lot of development and testing with samples, this restriction, which is not imported by default, creates additional works. And the `.meta` file will not be updated until I remove `~` and import it again. Also, the structure using `Samples~` or symbolic links makes it difficult to release using the old .unitypackage (some users are still develop their apps using .unitypackage because they want to tweak some code, or just don't want to use UPM).

Here's what I'd like to achieve:
- I'd like to have users import samples using UPM, but for me, I'd like to include samples in a project during development so that they can be easily developed.
- I want to be able to easily create an .unitypackage for those who don't use UPM.
- I want to develop in one repository and one project.

**Pull request merged**
